import {
  AccountInfoBase,
  AccountInfoWithBase64EncodedData,
  AccountMeta,
  Address,
  appendTransactionMessageInstruction,
  Base64EncodedDataResponse,
  createTransactionMessage,
  FetchAccountsConfig,
  GetMultipleAccountsApi,
  MaybeEncodedAccount,
  parseBase64RpcAccount,
  ReadonlyUint8Array,
  Rpc,
  Signature,
  Slot,
} from "@solana/kit";
import { chunks } from "../utils/common.js";
import { AddressInput, toAddress } from "../program/common.js";
import Provider, { getProvider } from "../provider.js";

/**
 * Sends a transaction to a program with the given accounts and instruction
 * data.
 */
export async function invoke(
  programId: AddressInput,
  accounts?: Array<AccountMeta>,
  data?: ReadonlyUint8Array,
  provider?: Provider
): Promise<Signature> {
  if (!provider) {
    provider = getProvider();
  }

  const message = appendTransactionMessageInstruction(
    {
      programAddress: toAddress(programId),
      accounts: accounts ?? [],
      ...(data ? { data } : {}),
    },
    createTransactionMessage({ version: 0 })
  );

  if (provider.sendAndConfirm === undefined) {
    throw new Error(
      "This function requires 'Provider.sendAndConfirm' to be implemented."
    );
  }

  return await provider.sendAndConfirm(message, []);
}

// The maximum number of addresses `getMultipleAccounts` accepts per request.
const GET_MULTIPLE_ACCOUNTS_LIMIT = 100;

/**
 * Fetches the given accounts as Kit `MaybeEncodedAccount`s, splitting the
 * request into batches of 100 addresses, the RPC limit.
 */
export async function getMultipleAccounts(
  rpc: Rpc<GetMultipleAccountsApi>,
  addresses: Address[],
  config?: FetchAccountsConfig
): Promise<MaybeEncodedAccount[]> {
  const batches = await getMultipleAccountsAndContext(rpc, addresses, config);
  return batches.flatMap((batch) => batch.accounts);
}

/**
 * Like {@link getMultipleAccounts}, but returns each batch alongside the
 * slot it was read at. Batches follow the order of the addresses.
 */
export async function getMultipleAccountsAndContext(
  rpc: Rpc<GetMultipleAccountsApi>,
  addresses: Address[],
  config: FetchAccountsConfig = {}
): Promise<{ accounts: MaybeEncodedAccount[]; context: { slot: Slot } }[]> {
  const { abortSignal, ...rpcConfig } = config;
  return await Promise.all(
    chunks(addresses, GET_MULTIPLE_ACCOUNTS_LIMIT).map(async (batch) => {
      const { value, context } = await rpc
        .getMultipleAccounts(batch, { ...rpcConfig, encoding: "base64" })
        .send({ abortSignal });
      return {
        accounts: value.map((account, index) =>
          parseBase64RpcAccount(batch[index], account)
        ),
        context,
      };
    })
  );
}

/**
 * The response of a successful transaction simulation, as returned by
 * `Provider.simulate`.
 */
export type SuccessfulTxSimulationResponse = {
  /**
   * Log messages emitted during the simulated execution, or `null` if the
   * simulation failed before the transaction could execute.
   */
  logs: readonly string[] | null;
  /** Post-simulation accounts, when requested. */
  accounts?:
    | readonly ((AccountInfoBase & AccountInfoWithBase64EncodedData) | null)[]
    | null;
  /** The number of compute units consumed by the simulated execution. */
  unitsConsumed?: bigint;
  /** The most recent return data generated by an instruction. */
  returnData?: {
    /** The return data itself, as base-64 encoded binary data. */
    data: Base64EncodedDataResponse;
    /** The program that generated the return data. */
    programId: Address;
  } | null;
};
