import { Buffer } from "buffer";
import {
  AccountInfoBase,
  AccountInfoWithBase64EncodedData,
  Address as KitAddress,
  Base64EncodedDataResponse,
} from "@solana/kit";
import {
  AccountInfo,
  AccountMeta,
  Connection,
  PublicKey,
  TransactionSignature,
  Transaction,
  TransactionInstruction,
  Commitment,
  Context,
} from "@solana/web3.js";
import { chunks } from "../utils/common.js";
import { Address, translateAddress } from "../program/common.js";
import Provider, { getProvider } from "../provider.js";

/**
 * Sends a transaction to a program with the given accounts and instruction
 * data.
 */
export async function invoke(
  programId: Address,
  accounts?: Array<AccountMeta>,
  data?: Buffer,
  provider?: Provider
): Promise<TransactionSignature> {
  programId = translateAddress(programId);
  if (!provider) {
    provider = getProvider();
  }

  const tx = new Transaction();
  tx.add(
    new TransactionInstruction({
      programId,
      keys: accounts ?? [],
      data,
    })
  );

  if (provider.sendAndConfirm === undefined) {
    throw new Error(
      "This function requires 'Provider.sendAndConfirm' to be implemented."
    );
  }

  return await provider.sendAndConfirm(tx, []);
}

const GET_MULTIPLE_ACCOUNTS_LIMIT: number = 99;

export async function getMultipleAccounts(
  connection: Connection,
  publicKeys: PublicKey[],
  commitment?: Commitment
): Promise<
  Array<null | { publicKey: PublicKey; account: AccountInfo<Buffer> }>
> {
  const results = await getMultipleAccountsAndContext(
    connection,
    publicKeys,
    commitment
  );
  return results.map((result) => {
    return result
      ? { publicKey: result.publicKey, account: result.account }
      : null;
  });
}

export async function getMultipleAccountsAndContext(
  connection: Connection,
  publicKeys: PublicKey[],
  commitment?: Commitment
): Promise<
  Array<null | {
    context: Context;
    publicKey: PublicKey;
    account: AccountInfo<Buffer>;
  }>
> {
  if (publicKeys.length <= GET_MULTIPLE_ACCOUNTS_LIMIT) {
    return await getMultipleAccountsAndContextCore(
      connection,
      publicKeys,
      commitment
    );
  } else {
    const batches = chunks(publicKeys, GET_MULTIPLE_ACCOUNTS_LIMIT);
    const results = await Promise.all<
      Array<null | {
        publicKey: PublicKey;
        account: AccountInfo<Buffer>;
        context: Context;
      }>
    >(
      batches.map((batch) =>
        getMultipleAccountsAndContextCore(connection, batch, commitment)
      )
    );
    return results.flat();
  }
}

async function getMultipleAccountsAndContextCore(
  connection: Connection,
  publicKeys: PublicKey[],
  commitmentOverride?: Commitment
): Promise<
  Array<null | {
    publicKey: PublicKey;
    account: AccountInfo<Buffer>;
    context: Context;
  }>
> {
  const commitment = commitmentOverride ?? connection.commitment;
  const { value: accountInfos, context } =
    await connection.getMultipleAccountsInfoAndContext(publicKeys, commitment);
  const accounts = accountInfos.map((account, idx) => {
    if (account === null) {
      return null;
    }
    return {
      publicKey: publicKeys[idx],
      account,
      context,
    };
  });

  return accounts;
}

/**
 * The response of a successful transaction simulation, as returned by
 * `Provider.simulate`.
 */
export type SuccessfulTxSimulationResponse = {
  /**
   * Log messages emitted during the simulated execution, or `null` if the
   * simulation failed before the transaction could execute.
   */
  logs: readonly string[] | null;
  /** Post-simulation accounts, when requested. */
  accounts?:
    | readonly ((AccountInfoBase & AccountInfoWithBase64EncodedData) | null)[]
    | null;
  /** The number of compute units consumed by the simulated execution. */
  unitsConsumed?: bigint;
  /** The most recent return data generated by an instruction. */
  returnData?: {
    /** The return data itself, as base-64 encoded binary data. */
    data: Base64EncodedDataResponse;
    /** The program that generated the return data. */
    programId: KitAddress;
  } | null;
};
