[package]
name = "anchor-attribute-constant"
version.workspace = true
publish = true
repository.workspace = true
license = "Apache-2.0"
description = "Anchor attribute macro for creating constant types"
edition = "2021"

[package.metadata.docs.rs]
workspace = true

[lib]
proc-macro = true

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
unimplemented = "deny"
indexing_slicing = "deny"

[features]
anchor-debug = ["anchor-syn/anchor-debug"]
idl-build = ["anchor-syn/idl-build"]

[dependencies]
anchor-syn = { workspace = true, optional = true }
quote = "1"
syn = { workspace = true, features = ["full"] }
