//! Test program exercising the remaining derive/attribute macros plus the
//! `Pod*` integer types inside a real SBF account.
//!
//! Covers:
//!   - `#[constant]` — attribute macro
//!   - `#[access_control(...)]` — attribute macro
//!   - `#[pod_wrapper]` — generates a Pod-safe enum wrapper
//!   - `#[derive(InitSpace)]` — computes borsh-serialized size at compile time
//!   - `PodU64` / `PodI32` / `PodBool` arithmetic + comparisons inside a
//!     zero-copy account (verifies pod.rs code paths run on SBF too).

extern crate alloc;

use anchor_lang::prelude::*;

declare_id!("Der1111111111111111111111111111111111111111");

// ---- #[constant] ----------------------------------------------------------

/// IDL-emitting bytes constant. The attribute also keeps the item
/// unchanged, so it compiles like a normal `pub const`.
#[constant]
pub const DATA_SEED: &[u8] = b"data-v2";

/// Numeric constant — exercises the `u8` branch of the IDL type mapping.
#[constant]
pub const MAX_DEPTH: u8 = 7;

// ---- #[pod_wrapper] -------------------------------------------------------

/// `#[repr(u8)]` enum with a Pod companion type (`PodMode`) generated by
/// `#[pod_wrapper]`. The companion wraps a `u8` and can sit inside a
/// `#[repr(C)]` zero-copy account without triggering bytemuck's
/// "every-bit-pattern-valid" unsoundness.
#[pod_wrapper]
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
#[repr(u8)]
pub enum Mode {
    Idle = 0,
    Active = 1,
    Halted = 2,
}

// ---- #[derive(InitSpace)] ------------------------------------------------

/// Borsh-encoded account. `InitSpace` computes `INIT_SPACE = 8 + 32 + 1 +
/// (4 + 4 * 8)` at compile time so `#[account(init, space = 8 + Profile::INIT_SPACE)]`
/// works without hardcoding a byte count.
#[account(borsh)]
#[derive(InitSpace)]
pub struct Profile {
    pub owner: Address,
    pub tier: u8,
    #[max_len(4)]
    pub scores: alloc::vec::Vec<u64>,
}

pub mod qualified {
    #[derive(anchor_lang::IdlType)]
    pub struct Inner {
        pub value: u64,
    }
}

pub mod limits {
    pub const ITEMS: usize = 3;
}

#[derive(IdlType)]
pub struct QualifiedUserTypeHolder<const N: usize> {
    pub authority: anchor_lang::prelude::Address,
    pub pinocchio_authority: pinocchio::address::Address,
    pub inner: qualified::Inner,
    pub literal_expr: [u8; 1 + 1],
    pub const_path: [u8; limits::ITEMS],
    pub bytes: [u8; N],
}

// ---- #[event] -------------------------------------------------------------

/// Default-mode event (Wincode with a borsh-compatible wire format).
/// `#[event]` derives `AnchorSerialize` and `AnchorDeserialize` automatically.
/// `emit!` serializes via `Event::data()` and calls `sol_log_data`, which
/// surfaces to clients as a `Program data: <base64>` log line.
#[event]
pub struct Bumped {
    pub amount: u64,
    pub step: i32,
    pub flag: bool,
}

/// Bytemuck-mode event — zero-copy `copy_nonoverlapping` of a `repr(C)`
/// struct. No dynamic sizing, but the cheapest emit path on SBF.
#[event(bytemuck)]
#[repr(C)]
pub struct SnapshotTaken {
    pub value: u64,
    pub mode: u8,
    pub _pad: [u8; 7],
}

// ---- Slab-backed account with pod integer fields --------------------------

/// Zero-copy account using PodU64/PodI32/PodBool so the exit-time write-back
/// exercises the Pod types' `Pod`/`Zeroable` impls end-to-end and the
/// arithmetic ops run inside the SBF VM.
#[account]
#[repr(C)]
pub struct Counter {
    pub value: PodU64,
    pub delta: PodI32,
    pub active: PodBool,
    pub mode: PodMode,
}

#[derive(IdlType)]
pub struct PairTupleIdl(pub u64, pub bool);

#[account]
#[repr(C)]
pub struct PodWrapperOnly {
    pub mode: PodMode,
}

#[account]
#[repr(C)]
pub struct PodVecOnly {
    pub items: PodVec<PodU64, 4>,
}

#[account]
#[repr(C, packed(1))]
pub struct PackedProducer {
    pub tag: u8,
    pub wide: u64,
}

#[event(bytemuck)]
#[repr(C, packed(1))]
pub struct PackedSnapshot {
    pub tag: u8,
    pub wide: u64,
}

// ---- Handlers -------------------------------------------------------------

#[program]
pub mod derives_test {
    use super::*;

    #[discrim = 0]
    pub fn initialize(ctx: &mut Context<Initialize>) -> Result<()> {
        ctx.accounts.counter.value = PodU64::from(0u64);
        ctx.accounts.counter.delta = PodI32::from(0i32);
        ctx.accounts.counter.active = PodBool::from(false);
        ctx.accounts.counter.mode = PodMode::Idle;
        Ok(())
    }

    /// Exercises Pod arithmetic + PodBool + pod_wrapper assignment on-chain.
    /// Also emits a default-mode Wincode event (automatically deriving
    /// `AnchorSerialize`) so the test can inspect the `Program data:` log line.
    #[discrim = 1]
    pub fn bump(ctx: &mut Context<Bump>, amount: u64, step: i32) -> Result<()> {
        let c = &mut ctx.accounts.counter;
        c.value = c.value + amount;
        c.delta = c.delta + step;
        c.active = PodBool::from(true);
        c.mode = PodMode::Active;
        emit!(Bumped {
            amount,
            step,
            flag: true,
        });
        Ok(())
    }

    /// Emits a bytemuck-mode event. Pure `sol_log_data` — no state changes.
    #[discrim = 5]
    pub fn snapshot(ctx: &mut Context<Bump>) -> Result<()> {
        let c = &ctx.accounts.counter;
        emit!(SnapshotTaken {
            value: c.value.get(),
            mode: c.mode.0,
            _pad: [0; 7],
        });
        Ok(())
    }

    /// Uses `checked_sub`/`saturating_sub` + comparison ops so the coverage
    /// trace hits the non-inlined arithmetic branches.
    #[discrim = 2]
    pub fn verify_invariants(ctx: &mut Context<Bump>) -> Result<()> {
        let c = &ctx.accounts.counter;
        // Comparison ops (PartialOrd + PartialEq<native>).
        if c.value == 0u64 {
            return Err(ProgramError::InvalidAccountData.into());
        }
        if c.value < PodU64::from(1u64) {
            return Err(ProgramError::InvalidAccountData.into());
        }
        // Checked arith — should succeed for values < MAX.
        let _ = c
            .value
            .checked_add(1u64)
            .ok_or(ProgramError::ArithmeticOverflow)?;
        let _ = c.value.saturating_sub(1u64);
        // pod_wrapper comparison crosses the PodMode ↔ Mode boundary.
        if c.mode == Mode::Idle {
            return Err(ProgramError::InvalidAccountData.into());
        }
        Ok(())
    }

    /// Runs two access-control checks before the body. The pre-checks use
    /// sibling fields via the `ctx.accounts.*` path, exactly matching the
    /// pattern the attribute macro is designed for.
    #[discrim = 3]
    #[access_control(require_authority(ctx), require_amount_under_cap(amount))]
    pub fn privileged(ctx: &mut Context<Privileged>, amount: u64) -> Result<()> {
        ctx.accounts.counter.value = c_add(ctx.accounts.counter.value, amount);
        Ok(())
    }

    /// Initializes a Profile account sized by `Profile::INIT_SPACE`. If the
    /// `#[derive(InitSpace)]` expansion computed a wrong value, either the
    /// account allocation would be wrong-sized or the borsh write inside
    /// this handler would fail at runtime.
    #[discrim = 4]
    pub fn init_profile(ctx: &mut Context<InitProfile>, tier: u8) -> Result<()> {
        let p = &mut ctx.accounts.profile;
        p.owner = *ctx.accounts.payer.account().address();
        p.tier = tier;
        p.scores = alloc::vec![10, 20, 30, 40];
        Ok(())
    }

    #[discrim = 6]
    pub fn const_array(
        _ctx: &mut Context<Bump>,
        bytes: [u8; limits::ITEMS],
    ) -> Result<[u8; limits::ITEMS]> {
        Ok(bytes)
    }
}

fn require_authority(ctx: &Context<Privileged>) -> Result<()> {
    if ctx.accounts.authority.account().address() != ctx.accounts.expected.account().address() {
        return Err(ProgramError::MissingRequiredSignature.into());
    }
    Ok(())
}

fn require_amount_under_cap(amount: u64) -> Result<()> {
    if amount >= (MAX_DEPTH as u64) * 1_000 {
        return Err(ProgramError::InvalidArgument.into());
    }
    Ok(())
}

fn c_add(p: PodU64, x: u64) -> PodU64 {
    p + x
}

// ---- Accounts structs -----------------------------------------------------

#[derive(Accounts)]
pub struct Initialize {
    #[account(mut)]
    pub payer: Signer,
    #[account(init, payer = payer, seeds = [DATA_SEED], bump)]
    pub counter: Account<Counter>,
    pub system_program: Program<System>,
}

#[derive(Accounts)]
pub struct Bump {
    #[account(mut, seeds = [DATA_SEED], bump)]
    pub counter: Account<Counter>,
}

#[derive(Accounts)]
pub struct Privileged {
    #[account(mut, seeds = [DATA_SEED], bump)]
    pub counter: Account<Counter>,
    pub authority: Signer,
    pub expected: UncheckedAccount,
}

#[derive(Accounts)]
pub struct InitProfile {
    #[account(mut)]
    pub payer: Signer,
    #[account(init, payer = payer, space = 8 + Profile::INIT_SPACE, seeds = [b"profile"], bump)]
    pub profile: BorshAccount<Profile>,
    pub system_program: Program<System>,
}

#[cfg(all(test, feature = "idl-build"))]
mod idl_tests {
    use super::*;

    #[test]
    fn idl_type_lowering_is_self_contained() {
        let type_def = <QualifiedUserTypeHolder<4> as IdlAccountType>::__idl_type_def()
            .expect("QualifiedUserTypeHolder should emit an IDL type");
        assert!(type_def.contains("\"name\":\"authority\",\"type\":\"pubkey\""));
        assert!(type_def.contains("\"name\":\"pinocchio_authority\",\"type\":\"pubkey\""));
        assert!(type_def.contains("\"defined\":{\"name\":\"Inner\"}"));
        assert!(!type_def.contains("qualified::Inner"));
        assert!(type_def.contains("\"array\":[\"u8\",2]"));
        assert!(type_def.contains("\"array\":[\"u8\",3]"));
        assert!(!type_def.contains("limits::ITEMS"));
        assert!(type_def
            .contains("\"generics\":[{\"kind\":\"const\",\"name\":\"N\",\"type\":\"usize\"}]"));
        assert!(type_def.contains("\"array\":[\"u8\",{\"generic\":\"N\"}]"));

        let mut accounts = alloc::vec::Vec::new();
        let mut types = alloc::vec::Vec::new();
        <QualifiedUserTypeHolder<4> as IdlAccountType>::__register_idl_deps(
            &mut accounts,
            &mut types,
        );
        assert!(types.iter().any(|ty| ty.contains("\"name\":\"Inner\"")));
    }

    #[test]
    fn idl_type_tuple_struct_preserves_unnamed_fields() {
        let type_def = <PairTupleIdl as IdlAccountType>::__idl_type_def()
            .expect("PairTupleIdl should emit an IDL type");
        assert!(type_def.contains("\"name\":\"PairTupleIdl\""));
        assert!(type_def.contains("\"kind\":\"struct\""));
        assert!(type_def.contains("\"fields\":[\"u64\",\"bool\"]"));
    }

    #[test]
    fn pod_wrapper_registers_alias_type_definition() {
        let type_def =
            <PodMode as IdlAccountType>::__IDL_TYPE_DEF.expect("PodMode should emit an IDL type");
        assert!(type_def.contains("\"name\":\"PodMode\""));
        assert!(type_def.contains("\"alias\":\"u8\""));

        let mut accounts = Vec::new();
        let mut types = Vec::new();
        <PodWrapperOnly as IdlAccountType>::__register_idl_deps(&mut accounts, &mut types);
        let wrapper_account = types
            .iter()
            .find(|entry| entry.contains("\"name\":\"PodWrapperOnly\""))
            .expect("PodWrapperOnly should emit its IDL type");
        assert!(wrapper_account.contains("\"defined\":{\"name\":\"PodMode\"}"));
        assert!(types.iter().any(|entry| entry.contains("\"name\":\"PodMode\"")));
    }

    #[test]
    fn pod_vec_registers_generic_layout_and_account_fields_use_generics() {
        let mut accounts = Vec::new();
        let mut types = Vec::new();
        <PodVecOnly as IdlAccountType>::__register_idl_deps(&mut accounts, &mut types);

        let pod_vec_account = types
            .iter()
            .find(|entry| entry.contains("\"name\":\"PodVecOnly\""))
            .expect("PodVecOnly should emit its IDL type");
        assert!(pod_vec_account.contains("\"defined\":{"));
        assert!(pod_vec_account.contains("\"name\":\"PodVec\""));
        assert!(pod_vec_account.contains("\"kind\":\"type\",\"type\":{\"defined\":{\"name\":\"PodU64\"}}"));
        assert!(pod_vec_account.contains("\"kind\":\"const\",\"value\":\"4\""));

        let pod_vec_type = types
            .iter()
            .find(|entry| {
                entry.contains("\"name\":\"PodVec\"")
                    && entry.contains("\"kind\":\"const\",\"name\":\"MAX\",\"type\":\"usize\"")
            })
            .expect("PodVec generic layout should be registered");
        assert!(pod_vec_type.contains("\"generics\":[{\"kind\":\"type\",\"name\":\"T\"},{\"kind\":\"const\",\"name\":\"MAX\",\"type\":\"usize\"}]"));
        assert!(pod_vec_type.contains("\"serialization\":\"bytemuckunsafe\""));
        assert!(pod_vec_type.contains("\"repr\":{\"kind\":\"c\"}"));
        assert!(pod_vec_type.contains("\"fields\":[{\"name\":\"len\",\"type\":{\"defined\":{\"name\":\"PodU16\"}}},{\"name\":\"data\",\"type\":{\"array\":[{\"generic\":\"T\"},{\"generic\":\"MAX\"}]}}]"));
    }

    #[test]
    fn packed_bytemuck_idl_preserves_packed_repr() {
        let type_def = <PackedProducer as IdlAccountType>::__idl_type_def()
            .expect("PackedProducer should emit an IDL type");
        assert!(type_def.contains("\"name\":\"PackedProducer\""));
        assert!(type_def.contains("\"serialization\":\"bytemuck\""));
        assert!(type_def.contains("\"repr\":{\"kind\":\"c\",\"packed\":true}"));
    }

    #[test]
    fn packed_bytemuck_event_idl_preserves_packed_repr() {
        let type_def = <PackedSnapshot as IdlAccountType>::__idl_type_def()
            .expect("PackedSnapshot should emit an IDL type");
        assert!(type_def.contains("\"name\":\"PackedSnapshot\""));
        assert!(type_def.contains("\"serialization\":\"bytemuck\""));
        assert!(type_def.contains("\"repr\":{\"kind\":\"c\",\"packed\":true}"));
    }
}
