//! Test program exercising the remaining derive/attribute macros plus the
//! `Pod*` integer types inside a real SBF account.
//!
//! Covers:
//!   - `#[constant]` — attribute macro
//!   - `#[access_control(...)]` — attribute macro
//!   - `#[pod_wrapper]` — generates a Pod-safe enum wrapper
//!   - `#[derive(InitSpace)]` — computes borsh-serialized size at compile time
//!   - `PodU64` / `PodI32` / `PodBool` arithmetic + comparisons inside a
//!     zero-copy account (verifies pod.rs code paths run on SBF too).

extern crate alloc;

use anchor_lang_v2::prelude::*;

declare_id!("Der1111111111111111111111111111111111111111");

// ---- #[constant] ----------------------------------------------------------

/// IDL-emitting bytes constant. The attribute also keeps the item
/// unchanged, so it compiles like a normal `pub const`.
#[constant]
pub const DATA_SEED: &[u8] = b"data-v2";

/// Numeric constant — exercises the `u8` branch of the IDL type mapping.
#[constant]
pub const MAX_DEPTH: u8 = 7;

// ---- #[pod_wrapper] -------------------------------------------------------

/// `#[repr(u8)]` enum with a Pod companion type (`PodMode`) generated by
/// `#[pod_wrapper]`. The companion wraps a `u8` and can sit inside a
/// `#[repr(C)]` zero-copy account without triggering bytemuck's
/// "every-bit-pattern-valid" unsoundness.
#[pod_wrapper]
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
#[repr(u8)]
pub enum Mode {
    Idle = 0,
    Active = 1,
    Halted = 2,
}

// ---- #[derive(InitSpace)] ------------------------------------------------

/// Borsh-encoded account. `InitSpace` computes `INIT_SPACE = 8 + 32 + 1 +
/// (4 + 4 * 8)` at compile time so `#[account(init, space = 8 + Profile::INIT_SPACE)]`
/// works without hardcoding a byte count.
#[account(borsh)]
#[derive(InitSpace)]
pub struct Profile {
    pub owner: Address,
    pub tier: u8,
    #[max_len(4)]
    pub scores: alloc::vec::Vec<u64>,
}

// ---- #[event] -------------------------------------------------------------

/// Default-mode event (wincode with a borsh-compatible wire format).
/// `emit!` serializes via `Event::data()` and calls `sol_log_data`, which
/// surfaces to clients as a `Program data: <base64>` log line.
#[event]
pub struct Bumped {
    pub amount: u64,
    pub step: i32,
    pub flag: bool,
}

/// Bytemuck-mode event — zero-copy `copy_nonoverlapping` of a `repr(C)`
/// struct. No dynamic sizing, but the cheapest emit path on SBF.
#[event(bytemuck)]
#[repr(C)]
pub struct SnapshotTaken {
    pub value: u64,
    pub mode: u8,
    pub _pad: [u8; 7],
}

// ---- Slab-backed account with pod integer fields --------------------------

/// Zero-copy account using PodU64/PodI32/PodBool so the exit-time write-back
/// exercises the Pod types' `Pod`/`Zeroable` impls end-to-end and the
/// arithmetic ops run inside the SBF VM.
#[account]
#[repr(C)]
pub struct Counter {
    pub value: PodU64,
    pub delta: PodI32,
    pub active: PodBool,
    pub mode: PodMode,
}

// ---- Handlers -------------------------------------------------------------

#[program]
pub mod derives_test {
    use super::*;

    #[discrim = 0]
    pub fn initialize(ctx: &mut Context<Initialize>) -> Result<()> {
        ctx.accounts.counter.value = PodU64::from(0u64);
        ctx.accounts.counter.delta = PodI32::from(0i32);
        ctx.accounts.counter.active = PodBool::from(false);
        ctx.accounts.counter.mode = PodMode::Idle;
        Ok(())
    }

    /// Exercises Pod arithmetic + PodBool + pod_wrapper assignment on-chain.
    /// Also emits a default-mode (wincode) event so the test can inspect the
    /// `Program data:` log line.
    #[discrim = 1]
    pub fn bump(ctx: &mut Context<Bump>, amount: u64, step: i32) -> Result<()> {
        let c = &mut ctx.accounts.counter;
        c.value = c.value + amount;
        c.delta = c.delta + step;
        c.active = PodBool::from(true);
        c.mode = PodMode::Active;
        emit!(Bumped {
            amount,
            step,
            flag: true,
        });
        Ok(())
    }

    /// Emits a bytemuck-mode event. Pure `sol_log_data` — no state changes.
    #[discrim = 5]
    pub fn snapshot(ctx: &mut Context<Bump>) -> Result<()> {
        let c = &ctx.accounts.counter;
        emit!(SnapshotTaken {
            value: c.value.get(),
            mode: c.mode.0,
            _pad: [0; 7],
        });
        Ok(())
    }

    /// Uses `checked_sub`/`saturating_sub` + comparison ops so the coverage
    /// trace hits the non-inlined arithmetic branches.
    #[discrim = 2]
    pub fn verify_invariants(ctx: &mut Context<Bump>) -> Result<()> {
        let c = &ctx.accounts.counter;
        // Comparison ops (PartialOrd + PartialEq<native>).
        if c.value == 0u64 {
            return Err(ProgramError::InvalidAccountData.into());
        }
        if c.value < PodU64::from(1u64) {
            return Err(ProgramError::InvalidAccountData.into());
        }
        // Checked arith — should succeed for values < MAX.
        let _ = c
            .value
            .checked_add(1u64)
            .ok_or(ProgramError::ArithmeticOverflow)?;
        let _ = c.value.saturating_sub(1u64);
        // pod_wrapper comparison crosses the PodMode ↔ Mode boundary.
        if c.mode == Mode::Idle {
            return Err(ProgramError::InvalidAccountData.into());
        }
        Ok(())
    }

    /// Runs two access-control checks before the body. The pre-checks use
    /// sibling fields via the `ctx.accounts.*` path, exactly matching the
    /// pattern the attribute macro is designed for.
    #[discrim = 3]
    #[access_control(require_authority(ctx), require_amount_under_cap(amount))]
    pub fn privileged(ctx: &mut Context<Privileged>, amount: u64) -> Result<()> {
        ctx.accounts.counter.value = c_add(ctx.accounts.counter.value, amount);
        Ok(())
    }

    /// Initializes a Profile account sized by `Profile::INIT_SPACE`. If the
    /// `#[derive(InitSpace)]` expansion computed a wrong value, either the
    /// account allocation would be wrong-sized or the borsh write inside
    /// this handler would fail at runtime.
    #[discrim = 4]
    pub fn init_profile(ctx: &mut Context<InitProfile>, tier: u8) -> Result<()> {
        let p = &mut ctx.accounts.profile;
        p.owner = *ctx.accounts.payer.account().address();
        p.tier = tier;
        p.scores = alloc::vec![10, 20, 30, 40];
        Ok(())
    }
}

fn require_authority(ctx: &Context<Privileged>) -> Result<()> {
    if ctx.accounts.authority.account().address() != ctx.accounts.expected.account().address() {
        return Err(ProgramError::MissingRequiredSignature.into());
    }
    Ok(())
}

fn require_amount_under_cap(amount: u64) -> Result<()> {
    if amount >= (MAX_DEPTH as u64) * 1_000 {
        return Err(ProgramError::InvalidArgument.into());
    }
    Ok(())
}

fn c_add(p: PodU64, x: u64) -> PodU64 {
    p + x
}

// ---- Accounts structs -----------------------------------------------------

#[derive(Accounts)]
pub struct Initialize {
    #[account(mut)]
    pub payer: Signer,
    #[account(init, payer = payer, seeds = [DATA_SEED], bump)]
    pub counter: Account<Counter>,
    pub system_program: Program<System>,
}

#[derive(Accounts)]
pub struct Bump {
    #[account(mut, seeds = [DATA_SEED], bump)]
    pub counter: Account<Counter>,
}

#[derive(Accounts)]
pub struct Privileged {
    #[account(mut, seeds = [DATA_SEED], bump)]
    pub counter: Account<Counter>,
    pub authority: Signer,
    pub expected: UncheckedAccount,
}

#[derive(Accounts)]
pub struct InitProfile {
    #[account(mut)]
    pub payer: Signer,
    #[account(init, payer = payer, space = 8 + Profile::INIT_SPACE, seeds = [b"profile"], bump)]
    pub profile: BorshAccount<Profile>,
    pub system_program: Program<System>,
}
